### ISSUE TITLE
Multiple javascript callbacks bug / Execute PL/SQL and return content plugin

### ISSUE THREAD

**Issue by fiala-lufi** [mortenbra/apex-plugins#9] opened 2021-06-16 07:23 UTC
Hi Morten,

i am using your plugin "Execute PL/SQL code and return content" in apex 20.2 application and i manage to find possible bug.

On one page i have 3 dynamic acntions (after page load). Each executes one "PL/SQL Code and return content" with different page element with different data using different page item. Every plugin action has 5s interval for refresh data. Mode is "Replace". The problem is in property "Javascript callback". Every action has setup different Javascript Callback (For Example: loadedA(); loadedB(); and loadedC();)

In page settings in "Function and Global Variable Declaration" definition i have declared all of these 3 JS functions and in everyone of them there is simple console.log("Callback A") with different last letter(A,B or C). The problem is, that somehow plugin register only first JS Function for callback even for the other two javascript callbacks. Result in console, is that there is 3times same text (Callback A).

Thanks for looking in to that and have a nice day ,

Lukas Fiala from Czechia

**Comment by mortenbra** [comment] 2021-06-16 18:40
Hi Lukas, I looked into this. The behavior is caused by the fact that the plugin emits Javascript using the apex_javascript.add_inline_code() procedure and always specifies the same value for the p_key parameter that APEX uses to determine whether the (same) Javascript has already been included on the page.

This is done to avoid having to include the same JS code repeatedly when you have multiple plugin instances on the page, but it also causes the callback part of the code to be fixed to whatever is emitted onto the page first.

Not sure if this is something that should be fixed. As a workaround, you do have access to a parameter called pElementName in your JS callback code. This will be equal to the name of the element (div) where the results of the PL/SQL gets emitted. So you can use the same callback for all your plugin instances on the page, and handle things differently based on the value of pElementName.

See attached images for an example.

![Capture1](https://user-images.githubusercontent.com/9341579/122274235-a1f43900-cee2-11eb-8351-78c0d59e2474.PNG)

![Capture2](https://user-images.githubusercontent.com/9341579/122274576-f8617780-cee2-11eb-8b38-fcf26fa8e7c1.PNG)

![Capture3](https://user-images.githubusercontent.com/9341579/122274585-fb5c6800-cee2-11eb-9a95-e7ff2e3c76fe.PNG)

**Comment by fiala-lufi** [comment] 2021-06-17 09:43
Thanks Morten. I handled the issue very similarly and i understand now why this behavior is like that.
Have a nice day, 
Lukas.

**Closed as completed** 2021-06-17 10:12 UTC
Labels: question
